import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import Password from 'antd/es/input/Password';
import { saveData, readData } from '../lib/file';


export interface Password {
  id: string
  subject: string
  algo: string
  hash: string
  createdAt: string
}

const initialState: Password[] = [];

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const readFromFile = createAsyncThunk(
  'password/readfromfile',
  async () => {
    try {
      const data = await readData();
      console.log("read data ok.");
      return data;
    } catch (e) {
      console.log("readfile error:", e);
    }
  }
);

export const saveToFile = createAsyncThunk(
  'password/savetofile',
  async (contents: string) => {
    try {
      await saveData(contents);
      console.log("save ok");
    } catch (e) {
      console.log("save data error:", e);
    }
  }
);


const passwordSlice = createSlice({
  name: 'password',
  initialState,
  reducers: {
    create: (state, action: PayloadAction<Password>) => {
      state.push(action.payload);
    },
    remove: (state, action: PayloadAction<string>) => {
      state.splice(state.findIndex(item => item.id === action.payload), 1);
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(saveToFile.fulfilled, (state, action) => {
        // ok
      })
      .addCase(readFromFile.fulfilled, (state, action) => {
        if (state.length === 0) {
          state.splice(0, state.length, ...JSON.parse(action.payload || "[]"))
          console.log("load to store.");
        }
      })
    // .addCase(incrementAsync.pending, (state) => {
    //   state.status = 'loading';
    // })
    // .addCase(incrementAsync.rejected, (state) => {
    //   state.status = 'failed';
    // });
  },
});


// export const selectPassword = (state: RootState) => state.password;
// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//     (dispatch, getState) => {
//       const currentValue = selectCount(getState());
//       if (currentValue % 2 === 1) {
//         dispatch(incrementByAmount(amount));
//       }
//     };

export default passwordSlice;